In [1]:
import numpy as np

##Datatypes and Attributes

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
a2 = np.array([[1,2,3],[2,4,8]])
a2

array([[1, 2, 3],
       [2, 4, 8]])

In [4]:
a2.shape


(2, 3)

In [5]:
a3 = np.array([[[1,2,3],
              [4,5,6],
              [7,8.5,9]],
               [[1,2,3],
               [4,5,6],
               [7,8,9]]])
a3

array([[[1. , 2. , 3. ],
        [4. , 5. , 6. ],
        [7. , 8.5, 9. ]],

       [[1. , 2. , 3. ],
        [4. , 5. , 6. ],
        [7. , 8. , 9. ]]])

In [6]:
a3.shape

(2, 3, 3)

In [7]:
a1.ndim, a2.ndim , a3.ndim

(1, 2, 3)

In [8]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('int32'), dtype('float64'))

In [9]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
#creating dataframe form numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  2  4  8

In [18]:
np.random.seed(0)
sales_amounts = np.random.randint(20,size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [20]:
daily_sales = pd.DataFrame(sales_amounts, index=["Mon","Tues","Wed","Thurs","Fri"],columns= ["Almond butter","Peanut butter","Cashew butter"])

In [21]:
daily_sales


Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [30]:
prices = np.array([10,8,12])
butter_prices = pd.DataFrame(prices.reshape(1,3),
                             index=["Price"],
                             columns= ["Almond butter","Peanut butter","Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [31]:
total_sales = prices.dot(sales_amounts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [32]:
prices.shape


(3,)

In [33]:
prices.shape, sales_amounts.shape

((3,), (5, 3))

In [34]:
total_sales = prices.dot(sales_amounts.T)

In [35]:
total_sales


array([240, 138, 458, 232, 142])

In [36]:
butter_prices.shape, daily_sales.shape

((1, 3), (5, 3))

In [37]:
daily = butter_prices.dot(daily_sales.T)
daily

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [38]:
daily_sales.dot(daily)

ValueError: matrices are not aligned

In [39]:
daily.shape,daily_sales.shape

((1, 5), (5, 3))

In [41]:
daily_sales["Total ($)"] = daily.T
daily_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

<img src="images/panda.png"/>

In [50]:
from matplotlib.image import imread
panda = imread("images/panda.png")
type(panda)

numpy.ndarray

In [52]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0